### ISSUE TITLE
Text is too small in the editor after upgrade (v5.1.0)

### ISSUE THREAD

**Issue by dec0dOS** [standardnotes/StyleKit#36]
Hello, Standard Notes team!

I've faced an issue during the development of my SN editors. After upgrading the dependencies, the text in the editor becomes really small.
The problem seems to be in the StyleKit.

stylekit v2.2.1:
![sn-stylekit_2 2 1_censored](https://user-images.githubusercontent.com/14824142/121789883-791e2c00-cbe2-11eb-987c-b0e246507b78.jpg)

stylekit v5.1.0:
![sn-stylekit_5 1 0_censored](https://user-images.githubusercontent.com/14824142/121789889-81766700-cbe2-11eb-8b57-557fe23c602a.jpg)

I'd like to know is that a bug/regression that needs to be fixed? If not, should I stay on sn-stylekit v2.2.1? 

By the way, I'm a huge fan of Standard Notes. I'm very grateful for all your work! If you need guidance to reproduce this bug, I'm glad to help!

**Comment by antsgar** [comment]
Hi @dec0dOS! 🙂 after StyleKit release 5.0.0, all font sizes and spacing variables are now set relative to the browser's font size (default is 16px), to improve accessibility. You can check the release notes here https://github.com/standardnotes/StyleKit/releases/tag/v5.0.0. Please refer to this PR https://github.com/standardnotes/StyleKit/pull/31 for instructions on how to update your editor so that the font size stays the same. If you have any questions please don't hesitate to reach out, I'll be happy to help!

**Comment by dec0dOS** [comment]
Hi @antsgar! Thanks a lot. It was required some minor changes to make it work as intended. I went by a different approach according to the updated StyleKit source code. It was much easier than I thought. 😅

**Comment by JaspalSuri** [comment]
That's great to hear, @dec0dOS; thanks for letting us know! 🙂
